__init__.py
from flask import Flask
from .views import views

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'yazlabScholar'

    
    
    app.register_blueprint(views,url_prefix = '/')
    
    return app

main.py
from website import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

views.py
from flask import Blueprint, render_template,request, redirect, url_for
from .dergipark_scraping import scrape_dergipark
from pymongo import MongoClient
from bson.objectid import ObjectId
from bson.errors import InvalidId

views = Blueprint('views', __name__)


client = MongoClient('localhost',27017)

db = client.dergi_flask
articles = db.articles


@views.route('/',methods=['POST','GET'])
def home():
    if request.method == 'POST':
        searchedWord = request.form['searchedWord']
        allResults = scrape_dergipark(searchedWord=searchedWord)
        return render_template("home.html",articles=allResults)
    return render_template("home.html")
    

@views.route('/search/<article_id>',methods = ['POST', 'GET'])
def search(article_id):
    article = articles.find_one({'_id': ObjectId(article_id)})
    return render_template("search.html",article=article)

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
    <title>Scholar Search</title>
</head>
<body>
    <div class="search">
        <form action="/" method="post">
            <input type="text" name = "searchedWord" placeholder="Arama kelimesini giriniz" required>
            <div class="buttonHolder">
                <button type="submit">Search</button>
            </div>
        </form>
    </div>
    <div class="container">
        <ul class="results">
            {% for article in articles %}
            <li class="article">
                <h3 class="article_name"><a href="{{ url_for('views.search',article_id=article['_id'])}}">{{article['name']}}</a></h3>
                <p class="pdf_link"><a href="{{article['pdfLink']}}">[PDF]</a></p>
                <p class="authors">
                    <b>{{article['authors']}}</b>
                </p>
                <p class="article_info">{{article['ozet']}}</p>
                <p class="article_abstract">{{article['yayimciAdi']}}</p>
                <p class="article_bottom">{{article['yayimTarihi']}}</p>
            </li>
            <hr>
            {% endfor %}
        </ul>
       
    </div>
</body>
</html>

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
    <title>{{ article['searchedWord'] }}</title>
</head>
<body>
    <div class="detail-container">
        
        <div class="details">
            <div class="article-title"><b>{{article['name']}}</b></h2>
                <div class="article-metadata">
                    <ul>
                        <li><p class="metadata"><b>{{article['authors']}}</b></p></li>
                        <li><p class="metadata">{{article['yayimTarihi']}}</p> </li>
                        <li> <p class="metadata">{{article['tur']}}</p></li>
                        <li> <p class="metadata">{{article['yayimciAdi']}}</p></li>
                        <li> <p class="metadata">{{article['doiNum']}}</p></li>
                        <li><p class="metadata">{{article['alintiSayisi']}}</p></li>
                    </ul>
                   
                </div>
                <div class="abstract">
                    <h2>Abstract</h2>
                    <p>{{article['ozet']}}</p>
                </div>
                <div class="keywords">
                    <p><b>{{article['keywords']}}</b></p>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>